#CXX = $(BINPREF)/g++ -std=gnu++11
include ${R_HOME}/etc${R_ARCH}/Makeconf
ADRM_DIR = adapterremoval
BT2_DIR = bowtie2

ifeq "$(WIN)" "64"

.PHONY:  clean all

all: 
	mkdir -p ../inst
	(cd	$(ADRM_DIR) && ($(MAKE) CXX="$(BINPREF)/g++ -std=gnu++11" -f Makefile.win))
	(cd $(BT2_DIR) && ($(MAKE) CXX="$(BINPREF)/g++" -f Makefile.win))



clean:
	(cd	$(ADRM_DIR) && ($(MAKE) clean -f Makefile))
	(cd	$(BT2_DIR) && ($(MAKE) clean -f Makefile.win))


else

.PHONY: clean all

all: 
	mkdir -p ../inst
	(cd	$(ADRM_DIR) && ($(MAKE) CXX="$(BINPREF)/g++ -std=gnu++11" -f Makefile.win))


clean:
	(cd	$(ADRM_DIR) && ($(MAKE) clean -f Makefile))

endif