// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// removeAdapter
int removeAdapter(Rcpp::CharacterVector argvs);
RcppExport SEXP _RBowtie2_removeAdapter(SEXP argvsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type argvs(argvsSEXP);
    rcpp_result_gen = Rcpp::wrap(removeAdapter(argvs));
    return rcpp_result_gen;
END_RCPP
}
// bowtie2Mapping
int bowtie2Mapping(Rcpp::CharacterVector argvs);
RcppExport SEXP _RBowtie2_bowtie2Mapping(SEXP argvsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type argvs(argvsSEXP);
    rcpp_result_gen = Rcpp::wrap(bowtie2Mapping(argvs));
    return rcpp_result_gen;
END_RCPP
}
// bowtie2Build
int bowtie2Build(Rcpp::CharacterVector argvs);
RcppExport SEXP _RBowtie2_bowtie2Build(SEXP argvsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type argvs(argvsSEXP);
    rcpp_result_gen = Rcpp::wrap(bowtie2Build(argvs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RBowtie2_removeAdapter", (DL_FUNC) &_RBowtie2_removeAdapter, 1},
    {"_RBowtie2_bowtie2Mapping", (DL_FUNC) &_RBowtie2_bowtie2Mapping, 1},
    {"_RBowtie2_bowtie2Build", (DL_FUNC) &_RBowtie2_bowtie2Build, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RBowtie2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
