# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

removeAdapter <- function(argvs) {
    .Call('_RBowtie2_removeAdapter', PACKAGE = 'RBowtie2', argvs)
}

bowtie2Mapping <- function(argvs) {
    .Call('_RBowtie2_bowtie2Mapping', PACKAGE = 'RBowtie2', argvs)
}

bowtie2Build <- function(argvs) {
    .Call('_RBowtie2_bowtie2Build', PACKAGE = 'RBowtie2', argvs)
}

